### ISSUE TITLE
Data Ingestion from 3rd Party REST-API Data Sources

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Backend#15]
We need to be able to connect the 3rd party REST-APIs as data sources for the RADAR Platform (this might be anything from Google Fit, Fitbit, Withings etc). Granted there are potentially a numer of considerations like pull/pubsub, different auth mechanisms etc. But it would be useful to explore how generalized a solution could be built. Perhaps as a starting point one might look at the Open mHealth Shimmer and similar attempts at this.

**Comment by fnobilia** [comment]
We could develop a `Kafka Sink Connector` that interacts with 3rd party APIs. This connector will have multiple `reader`s one per 3rd party API. A `reader` is a java class that convert the 3rd party response to Avro.

**Comment by blootsvoets** [comment]
A Kafka Source connector right? For ingesting data into kafka.

**Comment by fnobilia** [comment]
@blootsvoets of corse yes!

**Comment by blootsvoets** [comment]
Move ingestion to separate source connectors.
