### ISSUE TITLE
Volume API

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-Backend#30]
It would be great to have an API that sends the aggregated volume of the sensors for the dashboard.

In the dashboard, we have a graph that represents the volume of visible sensors that is used to zoom in or out of the data in time.

This is the detail of the volume graph:
![screen shot 2017-08-18 at 12 28 37](https://user-images.githubusercontent.com/125300/29452982-cd788494-8410-11e7-8d9c-8e9ce2afbd14.png)
https://github.com/RADAR-CNS/RADAR-Design/blob/master/Screens/%5BDesktop%5D%20400-Patient-Overlay.png

Ideally, the API request would take an object of sources and an array of sensors to be aggregated.

Request with a JSON body.
```
POST /data/volume/{subjectId}

{
  "00:07:80:1F:53:1A": ["ACCELEROMETER", "BATTERY"],
  "00:07:80:1F:53:1B": ["THERMOMETER", "ELECTRODERMAL_ACTIVITY"],
  "00:07:80:1F:53:1C": ["THERMOMETER", "HEART_RATE"],
  "00:07:80:1F:53:1D": ["BLOOD_VOLUME_PULSE", "INTER_BEAT_INTERVAL"]
}
```

Response
```json
{
  "header": {
    "subjectId": "MRC03",
    "sources": {
      "00:07:80:1F:53:1A": ["ACCELEROMETER", "BATTERY"],
      "00:07:80:1F:53:1B": ["THERMOMETER", "ELECTRODERMAL_ACTIVITY"],
      "00:07:80:1F:53:1C": ["THERMOMETER", "HEART_RATE"],
      "00:07:80:1F:53:1D": ["BLOOD_VOLUME_PULSE", "INTER_BEAT_INTERVAL"]
    },
    "descriptiveStatistic": "RECEIVED_MESSAGES",
    "unit": "VOLUME",
    "timeFrame": "TEN_SECOND",
    "max": 5,
    "effectiveTimeFrame": {
      "startDateTime": "2017-07-03T12:38:40Z",
      "endDateTime": "2017-07-03T12:39:40Z"
    }
  },
  "dataset": [
    {
      "value": 0,
      "startDateTime": "2017-07-03T12:38:40Z"
    },
    {
      "value": 5,
      "startDateTime": "2017-07-03T12:38:50Z"
    },
    {
      "value": 4,
      "startDateTime": "2017-07-03T12:39:00Z"
    },
    {
      "value": 0,
      "startDateTime": "2017-07-03T12:39:10Z"
    },
    {
      "value": 1,
      "startDateTime": "2017-07-03T12:39:20Z"
    },
    {
      "value": 2,
      "startDateTime": "2017-07-03T12:39:30Z"
    }
  ]
}

```

**Comment by kerzmaximilian** [comment]
Thanks for putting this together @herkulano. 
@fnobilia, we've reached a point where the dashboard needs to make a request for each sensor and some considerable aggregation to generate a vector that supports the above. Let's discuss this on Monday.

**Comment by fnobilia** [comment]
As agreed with @afolarin @kerzmaximilian @mpgxvii, we will deploy a solution based on Apache Kafka and REST-Api. We will create `streams` to compute:
- volume for each subject
- volume for all active sources for the given subject 
- volume for all passive sources for the given subject 

For better support the `study view`:
- a rest function will be created to provide the `devices status` (the query will use the volume at subject level). The `compliance graph` will be supported using the active and passive volume.
- a rest function will be created to provide the `last update` value for each subject.

`gender` and `DOB` will be accessible using new rest end points that will come after the integration go the Management Portal. I will check this with @dennyverbeeck

**Comment by herkulano** [comment]
Issue moved to [RADAR-CNS/RADAR-RestApi #39](https://github.com/RADAR-CNS/RADAR-RestApi/issues/39) via [**ZenHub**](https://www.zenhub.com/)
