### ISSUE TITLE
How to link/unlink devices to users

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Backend#6]
We need a mechanism to link/unlink users to the devices.

**Comment by blootsvoets** [comment]
See [our private google doc](https://docs.google.com/a/thehyve.nl/document/d/1v7yq5BGWp8bGEIzQ3--wZ_zwAMLGEiUCfFRoY-samgA) for a proposal.

**Comment by blootsvoets** [comment]
Solved in management portal.
