### ISSUE TITLE
New Confluent Platform

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Backend#7]
The [new Confluent Platform](https://www.confluent.io/blog/announcing-confluent-3-1-with-apache-kafka-0-10-1-0/) has been released. We should evaluate whether updating our clusters is worthwhile.

**Comment by afolarin** [comment]
If you are not I'll roll back to 3.0.0 on the RADAR-CNS/RADAR-Docker -- I'm using 3.1.0

**Comment by fnobilia** [comment]
The two EC2 instances have 3.0.1. I think we can update our version. There is time to test everything before the pilot study. @blootsvoets  @MaximMoinat @nivemaham
